### ISSUE TITLE
travel is unable to travel to gray island through NPC Captain Seahorse

### ISSUE THREAD

**Issue by WeskerPower** [Tibia-WindBot/lucas-library#6] opened 2017-01-08 09:14 UTC
12:24:55 Unable to travel to 'gray island' through NPC 'Captain Seahorse'. DestinationPos: 33190,31984,7

correct pos = 33196, 31984, 7

--------------------
Server Count
wont display the correct amount "rings of healing"
servercount("ring of healing") reads 1
servercount("rings of healing") reads + 1

**Comment by rmobis** [comment] 2017-01-09 20:01
I'll investigate the `travel` problem. Can you provide a script where this happens?

---
`servercount` is not a library function, please make a report on the forums.

**PS:** On further problems, please open _one_ issue per problem.

**Comment by WeskerPower** [comment] 2017-01-10 22:28
travel edron to gray island it says it cant take you there its just a position error
correct pos = 33196, 31984, 7

**Comment by rmobis** [comment] 2017-01-18 17:12
@WeskerPower I'm unable to reproduce the error. I tried the code you suggested and it worked just fine.

**Comment by Mistgun** [comment] 2017-01-18 18:59
Seems like it travels correctly, but destin pos is not correct. I checked it myself and correct pos is:
33196 31984 7 which Wesker already gave here.

**Comment by rmobis** [comment] 2017-01-31 14:10
This was fixed on #12 and released on 16.8.

**Closed as completed by rmobis** 2017-01-31 14:10 UTC
Labels: bug, up-for-grabs
